version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_api
    env_file: .env
    ports:
      - "8080:3000"
    depends_on:
      - mongo
      - redis
    command: npm run start:prod
    environment:
      MONGO_URI: ${DATABASE_URL}
      REDIS_URI: ${REDIS_URL}

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data/db
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      REDIS_URL: ${REDIS_URL}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}


volumes:
  mongo_data:
  redis_data: